[package]
name = "lightweaver"
version = "0.1.0"
edition = "2021"

[dependencies]
png = "0.17.16"

lw_proc_macros = { path = "./lw_proc_macros" }
gc-arena = "0.5.3"
anyhow = "1.0.102"
thiserror = "2.0.18"
log = "0.4.29"
cgmath = "0.18.0"
pretty_env_logger = "0.5.0"
vulkanalia = { version = "0.35.0", features = ["libloading", "provisional", "window"] }
winit = "0.30.13"
tobj = "4.0.3"
